version: "3.6"

services:
#
# SEGUIDOR DE WEBS ( SERIES, PELICULES, LLIBRES, ETC... )
#
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9191:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${STORAGE}/config/jackett:/config
      - ${STORAGE}/transmission:/downloads