version: "3.6"

services:
#
# NGINX-PROXY-MANAGER - PROXY INVERSO
#
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '9081:81' # Admin Web Port
    volumes:
      - ${STORAGE}/config/npm/data:/data
      - ${STORAGE}/config/npm/letsencrypt:/etc/letsencrypt