version: "3.6"

services:
#
# JELLYFIN - GESTOR PELICULAS, SERIES
#
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${STORAGE}/config/jellyfin:/config
      - ${MEDIA}/series:/data/tvshows
      - ${MEDIA}/movies:/data/movies 